# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y build-essential libalut-dev libasound2-dev libc6-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev mesa-utils pkg-config xorg-dev xvfb

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Test
        env:
          DISPLAY: ":99.0"
        run: xvfb-run --auto-servernum  go test -race -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

      - name: Build
        env:
          GOOS: js
          GOARCH: wasm
        run: go build -v -o web/asteroids.wasm

      - name: Copy files
        run: cp -av $(go env GOROOT)/misc/wasm/wasm_exec.js web/

      - name: Configure Github Pages
        uses: actions/configure-pages@v2

      - name: Upload WASM artifacts 
        uses: actions/upload-pages-artifact@v1
        with:
          path: web/

      - id: deployment
        name: Deploy to Github Pages
        uses: actions/deploy-pages@v1
